server:
   port: 8501
   #servlet:
    #context-path: /dt
   address: 0.0.0.0 #启用外部IP访问
spring:
   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true
   messages:
      encoding: UTF-8
   mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
   datasource:
      username: root
      password: '!Q@W3e4r' #特殊字符需要单引号
      url: jdbc:mysql:///db_mybatis?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
   application:
    name: springbootweb

mybatis:
  mapperLocations: classpath:mapper/*.xml #就是.xml文件的位置，如果没有配置，就默认去mapper接口类所在的包中去找
  #config-location: classpath:mybatis-config.xml
  typeAliasesPackage: com.cykj.springbootweb.entity     

         
  